import {
  DECK_REMOVE_PRIZE_LABEL,
  DECK_UPGRADE_PRIZE_LABEL,
  deckAddPrizeLabel,
} from "../../deck/sliceLabels";
import { perkPrizeLabel } from "../../perks/perkDisplay";
import type { PrizeDef } from "./types";

/**
 * Prize library — reusable outcomes referenced by id in `wheelDatabase.ts`.
 * Add new prizes here, then reference them as `{ prize: "your_id", chance: 10 }`.
 */
export const PRIZE_CATALOG = {
  money_5: {
    kind: "money",
    label: "+$5",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 5 },
  },
  money_10: {
    kind: "money",
    label: "+$10",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 10 },
  },
  money_15: {
    kind: "money",
    label: "+$15",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 15 },
  },
  money_20: {
    kind: "money",
    label: "+$20",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 20 },
  },
  money_25: {
    kind: "money",
    label: "+$25",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 25 },
  },
  money_loss_5: {
    kind: "money_loss",
    label: "-$5",
    icon: "money-off",
    iconFamily: "MaterialIcons",
    weightTags: ["negative"],
    payload: { moneyDelta: -5 },
  },
  money_loss_10: {
    kind: "money_loss",
    label: "-$10",
    icon: "money-off",
    iconFamily: "MaterialIcons",
    weightTags: ["negative"],
    payload: { moneyDelta: -10 },
  },
  money_loss_15: {
    kind: "money_loss",
    label: "-$15",
    icon: "money-off",
    iconFamily: "MaterialIcons",
    weightTags: ["negative"],
    payload: { moneyDelta: -15 },
  },
  money_loss_20: {
    kind: "money_loss",
    label: "-$20",
    icon: "money-off",
    iconFamily: "MaterialIcons",
    weightTags: ["negative"],
    payload: { moneyDelta: -20 },
  },
  money_loss_25: {
    kind: "money_loss",
    label: "-$25",
    icon: "money-off",
    iconFamily: "MaterialIcons",
    weightTags: ["negative"],
    payload: { moneyDelta: -25 },
  },
  money_30: {
    kind: "money",
    label: "+$30",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 30 },
  },
  money_50: {
    kind: "money",
    label: "+$50",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 50 },
    presentation: { colorIndex: 0 },
  },
  money_80: {
    kind: "money",
    label: "+$80",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 80 },
  },
  money_100: {
    kind: "money",
    label: "+$100",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 100 },
  },
  money_120: {
    kind: "money",
    label: "+$120",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 120 },
  },
  money_150: {
    kind: "money",
    label: "+$150",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 150 },
  },
  money_200: {
    kind: "money",
    label: "+$200",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 200 },
  },
  money_300: {
    kind: "money",
    label: "+$300",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 300 },
  },
  money_500: {
    kind: "money",
    label: "+$500",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { moneyDelta: 500 },
  },
  money_600: {
    kind: "money",
    label: "+$60",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 60 },
  },
  money_800: {
    kind: "money",
    label: "JACKPOT +$800",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { moneyDelta: 800 },
  },
  money_1000: {
    kind: "money",
    label: "JACKPOT +$1000",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { moneyDelta: 1000 },
  },
  money_loss_40: {
    kind: "money_loss",
    label: "-$40",
    icon: "money-off",
    iconFamily: "MaterialIcons",
    weightTags: ["negative"],
    payload: { moneyDelta: -40 },
  },
  money_loss_50: {
    kind: "money_loss",
    label: "-$50",
    icon: "money-off",
    iconFamily: "MaterialIcons",
    weightTags: ["negative"],
    payload: { moneyDelta: -50 },
  },
  money_loss_60: {
    kind: "money_loss",
    label: "-$60",
    icon: "money-off",
    iconFamily: "MaterialIcons",
    weightTags: ["negative"],
    payload: { moneyDelta: -60 },
  },
  money_loss_80: {
    kind: "money_loss",
    label: "-$80",
    icon: "money-off",
    iconFamily: "MaterialIcons",
    weightTags: ["negative"],
    payload: { moneyDelta: -80 },
  },
  money_loss_100: {
    kind: "money_loss",
    label: "-$100",
    icon: "money-off",
    iconFamily: "MaterialIcons",
    weightTags: ["negative"],
    payload: { moneyDelta: -100 },
  },
  money_loss_150: {
    kind: "money_loss",
    label: "-$150",
    icon: "money-off",
    iconFamily: "MaterialIcons",
    weightTags: ["negative", "stakes"],
    payload: { moneyDelta: -150 },
  },
  money_loss_200: {
    kind: "money_loss",
    label: "-$200",
    icon: "money-off",
    iconFamily: "MaterialIcons",
    weightTags: ["negative"],
    payload: { moneyDelta: -200 },
  },
  bank_cut_half: {
    kind: "bank_cut",
    label: "−25%",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["negative", "stakes"],
    payload: { bankPercent: -0.25 },
  },
  bank_cut_ten: {
    kind: "bank_cut",
    label: "−10%",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["negative", "stakes"],
    payload: { bankPercent: -0.1 },
  },
  bank_cut_quarter: {
    kind: "bank_cut",
    label: "−15%",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["negative", "stakes"],
    payload: { bankPercent: -0.15 },
  },
  bank_loss_5: {
    kind: "bank_cut",
    label: "−5%",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["negative", "stakes"],
    payload: { bankPercent: -0.05 },
  },
  bank_loss_10: {
    kind: "bank_cut",
    label: "−10%",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["negative", "stakes"],
    payload: { bankPercent: -0.1 },
  },
  bank_loss_15: {
    kind: "bank_cut",
    label: "−15%",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["negative", "stakes"],
    payload: { bankPercent: -0.15 },
  },
  bank_loss_25: {
    kind: "bank_cut",
    label: "−25%",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["negative", "stakes"],
    payload: { bankPercent: -0.25 },
  },
  bank_loss_30: {
    kind: "bank_cut",
    label: "−30%",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["negative", "stakes"],
    payload: { bankPercent: -0.3 },
  },
  bank_loss_40: {
    kind: "bank_cut",
    label: "−40%",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["negative", "stakes"],
    payload: { bankPercent: -0.4 },
  },
  bank_cut_75: {
    kind: "bank_cut",
    label: "−75%",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["negative", "stakes"],
    payload: { bankPercent: -0.75 },
  },
  bank_gain_5: {
    kind: "bank_cut",
    label: "+5%",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { bankPercent: 0.05 },
  },
  bank_gain_10: {
    kind: "bank_cut",
    label: "+10%",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { bankPercent: 0.1 },
  },
  bank_gain_15: {
    kind: "bank_cut",
    label: "+15%",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { bankPercent: 0.15 },
  },
  bank_gain_25: {
    kind: "bank_cut",
    label: "+25%",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { bankPercent: 0.25 },
  },
  bank_gain_30: {
    kind: "bank_cut",
    label: "+30%",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { bankPercent: 0.3 },
  },
  bank_gain_40: {
    kind: "bank_cut",
    label: "+40%",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { bankPercent: 0.4 },
  },
  bank_gain_4: {
    kind: "bank_cut",
    label: "+10%",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { bankPercent: 0.1 },
  },
  bank_gain_7: {
    kind: "bank_cut",
    label: "+25%",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { bankPercent: 0.25 },
  },
  bank_wipe: {
    kind: "bank_wipe",
    label: "LOSE ALL",
    icon: "account-balance-wallet",
    iconFamily: "MaterialIcons",
    weightTags: ["negative", "stakes", "rare"],
    payload: { wipeBank: true },
    presentation: { rarity: "rare" },
  },
  bank_double: {
    kind: "bank_cut",
    label: "+100%",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { bankPercent: 1 },
  },
  perk_lucky_money: {
    kind: "perk",
    label: perkPrizeLabel("lucky_money"),
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "lucky_money" },
    presentation: { rarity: "rare" },
  },
  perk_lucky_perk: {
    kind: "perk",
    label: perkPrizeLabel("lucky_perk"),
    icon: "auto-awesome",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "lucky_perk" },
    presentation: { rarity: "rare" },
  },
  perk_lucky_streak: {
    kind: "perk",
    label: perkPrizeLabel("lucky_streak"),
    icon: "stars",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "lucky_streak" },
    presentation: { rarity: "rare" },
  },
  perk_gold_rush: {
    kind: "perk",
    label: perkPrizeLabel("gold_rush"),
    icon: "trending-up",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "gold_rush" },
    presentation: { rarity: "rare" },
  },
  perk_iron_reserve: {
    kind: "perk",
    label: "Iron Shield",
    icon: "shield",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "iron_reserve" },
  },
  perk_safe_harbor: {
    kind: "perk",
    label: "Safe Harbor",
    icon: "security",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "safe_harbor" },
  },
  perk_high_roller: {
    kind: "perk",
    label: perkPrizeLabel("high_roller"),
    icon: "casino",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "high_roller" },
  },
  perk_hot_table: {
    kind: "perk",
    label: "Hot Table",
    icon: "whatshot",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "hot_table" },
  },
  perk_double_down: {
    kind: "perk",
    label: "Double Down",
    icon: "exposure-plus-1",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "double_down" },
  },
  perk_vip_roller: {
    kind: "perk",
    label: perkPrizeLabel("vip_roller"),
    icon: "workspace-premium",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "vip_roller" },
  },
  perk_ante_insurance: {
    kind: "perk",
    label: "Cycle Cushion",
    icon: "policy",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "ante_insurance" },
  },
  deck_copper_chip: {
    kind: "deck_add",
    label: deckAddPrizeLabel("copper_chip"),
    icon: "paid",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { cardId: "copper_chip" },
  },
  deck_weighted_die: {
    kind: "deck_add",
    label: deckAddPrizeLabel("weighted_die"),
    icon: "casino",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { cardId: "weighted_die" },
  },
  deck_upgrade: {
    kind: "deck_upgrade",
    label: DECK_UPGRADE_PRIZE_LABEL,
    icon: "upgrade",
    iconFamily: "MaterialCommunityIcons",
    payload: {},
  },
  deck_remove: {
    kind: "deck_remove",
    label: DECK_REMOVE_PRIZE_LABEL,
    icon: "delete-outline",
    iconFamily: "MaterialIcons",
    weightTags: ["negative"],
    payload: {},
  },
  debuff_debt_mark: {
    kind: "debuff",
    label: "Debt Mark",
    icon: "skull-crossbones",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["negative"],
    payload: { debuffId: "debt_mark" },
  },
  debuff_rusted: {
    kind: "debuff",
    label: "Rusted",
    icon: "cog-off",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["negative"],
    payload: { debuffId: "rusted_gear" },
  },
  relic_lucky_coin: {
    kind: "relic_offer",
    label: "Lucky Coin",
    icon: "circle-multiple",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["rare"],
    payload: { relicId: "lucky_coin" },
  },
  relic_void_lens: {
    kind: "relic_offer",
    label: "Void Lens",
    icon: "blur-circular",
    iconFamily: "MaterialIcons",
    weightTags: ["rare"],
    payload: { relicId: "void_lens" },
  },
  perk_compounder: {
    kind: "perk",
    label: "Compounder",
    icon: "savings",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "compounder" },
    presentation: { rarity: "rare" },
  },
  perk_coupon_king: {
    kind: "perk",
    label: "Coupon King",
    icon: "sell",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "coupon_king" },
  },
  perk_final_guard: {
    kind: "perk",
    label: perkPrizeLabel("final_guard"),
    icon: "shield-sword",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "final_guard" },
    presentation: { rarity: "rare" },
  },
  perk_final_tax_shield: {
    kind: "perk",
    label: perkPrizeLabel("final_tax_shield"),
    icon: "shield-account",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "final_tax_shield" },
    presentation: { rarity: "rare" },
  },
  perk_clutch_cash: {
    kind: "perk",
    label: perkPrizeLabel("clutch_cash"),
    icon: "cash-fast",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "clutch_cash" },
    presentation: { rarity: "rare" },
  },
  deck_purity_charm: {
    kind: "deck_add",
    label: deckAddPrizeLabel("purity_charm"),
    icon: "security",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { cardId: "purity_charm" },
  },
  builder_wedge_money: {
    kind: "booster",
    label: "+1 $ wedge",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { sliceDelta: 1 },
    presentation: { rarity: "rare" },
  },
  builder_wedge_percent: {
    kind: "booster",
    label: "+1 % wedge",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { sliceDelta: 1 },
    presentation: { rarity: "rare" },
  },
  builder_wedge_perk: {
    kind: "booster",
    label: "+1 perk wedge",
    icon: "auto-awesome",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { sliceDelta: 1 },
    presentation: { rarity: "rare" },
  },
  builder_wedge_drain: {
    kind: "booster",
    label: "+1 drain wedge",
    icon: "trending-down",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { sliceDelta: 1 },
    presentation: { rarity: "rare" },
  },
  builder_wedge_lucky: {
    kind: "booster",
    label: "+1 lucky wedge",
    icon: "emoji-events",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { sliceDelta: 1 },
    presentation: { rarity: "rare" },
  },
  builder_wedge_chaos: {
    kind: "booster",
    label: "+1 chaos wedge",
    icon: "shuffle",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { sliceDelta: 1 },
    presentation: { rarity: "rare" },
  },
  neutral_calm: {
    kind: "neutral",
    label: "Calm",
    icon: "spa",
    iconFamily: "MaterialIcons",
    payload: {},
  },
  neutral_hold: {
    kind: "neutral",
    label: "Hold",
    icon: "pan-tool",
    iconFamily: "MaterialIcons",
    payload: {},
  },
  neutral_focus: {
    kind: "neutral",
    label: "Focus",
    icon: "center-focus-strong",
    iconFamily: "MaterialIcons",
    payload: {},
  },
  neutral_gamble: {
    kind: "neutral",
    label: "Gamble",
    icon: "casino",
    iconFamily: "MaterialIcons",
    payload: {},
  },
  neutral: {
    kind: "neutral",
    label: "—",
    icon: "do-not-disturb",
    iconFamily: "MaterialIcons",
    payload: {},
  },
  debt_bomb: {
    kind: "run_effect",
    label: "Debt Bomb",
    icon: "bomb",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["negative", "stakes"],
    payload: { runEffectId: "debt_bomb" },
    presentation: { rarity: "rare" },
  },
  lock_drain: {
    kind: "run_effect",
    label: "Lock",
    icon: "lock-alert",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["negative"],
    payload: { runEffectId: "lock_drain" },
  },
  boss_ghost: {
    kind: "run_effect",
    label: "Boss Ghost",
    icon: "visibility",
    iconFamily: "MaterialIcons",
    weightTags: ["negative", "rare"],
    payload: { runEffectId: "boss_ghost" },
  },
  corruption_spread: {
    kind: "run_effect",
    label: "Corruption",
    icon: "biohazard",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["negative", "rare"],
    payload: { runEffectId: "corruption_spread" },
  },
  doom_spiral: {
    kind: "run_effect",
    label: "Doom Spiral",
    icon: "hurricane",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["negative", "rare"],
    payload: { runEffectId: "doom_spiral" },
    presentation: { rarity: "rare" },
  },
  mega_money: {
    kind: "money",
    label: "MEGA +$800",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { moneyDelta: 800 },
    presentation: { rarity: "rare" },
  },
  boss_pay_100: {
    kind: "money",
    label: "+$100",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 100 },
  },
  boss_pay_150: {
    kind: "money",
    label: "+$150",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 150 },
  },
  neutral_hold_line: {
    kind: "neutral",
    label: "Hold Line",
    icon: "pause-circle-outline",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["neutral"],
    payload: {},
  },
  boss_perk_tax: {
    kind: "run_effect",
    label: "Perk Tax",
    icon: "account-cash",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["negative", "stakes"],
    payload: { runEffectId: "boss_perk_tax" },
  },
  boss_overhead: {
    kind: "run_effect",
    label: "Table Fee",
    icon: "cash-minus",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["negative", "stakes"],
    payload: { runEffectId: "boss_overhead" },
  },
  boss_shield_break: {
    kind: "run_effect",
    label: "Shield Break",
    icon: "shield-off",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["negative", "stakes"],
    payload: { runEffectId: "boss_shield_break" },
  },
  boss_chip_cache: {
    kind: "run_effect",
    label: "Chip Cache",
    icon: "treasure-chest",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["positive", "rare"],
    payload: { runEffectId: "boss_chip_cache" },
    presentation: { rarity: "rare" },
  },
  boss_golden_seal: {
    kind: "run_effect",
    label: "Golden Seal",
    icon: "seal",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["positive", "rare"],
    payload: { runEffectId: "boss_golden_seal" },
    presentation: { rarity: "rare" },
  },
  boss_relic_crown: {
    kind: "relic_offer",
    label: "Crown Relic",
    icon: "crown",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["positive", "rare"],
    payload: { relicId: "hot_hand" },
    presentation: { rarity: "rare" },
  },
  boss_mystery_perk: {
    kind: "perk",
    label: perkPrizeLabel("lucky_streak"),
    icon: "help-circle",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "lucky_streak" },
    presentation: { rarity: "rare" },
  },
  mega_curse: {
    kind: "debuff",
    label: "Mega Curse",
    icon: "fire-alert",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["negative", "rare"],
    payload: { debuffId: "curse_of_greed" },
    presentation: { rarity: "rare" },
  },
  triple_perk: {
    kind: "perk",
    label: perkPrizeLabel("hot_table"),
    icon: "whatshot",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "hot_table" },
    presentation: { rarity: "rare" },
  },
  boss_relic: {
    kind: "relic_offer",
    label: "Boss Relic",
    icon: "sword-cross",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["rare"],
    payload: { relicId: "boss_slayer" },
    presentation: { rarity: "rare" },
  },
} as const satisfies Record<string, PrizeDef>;

export type PrizeCatalogId = keyof typeof PRIZE_CATALOG;
