import type { PrizeDef } from "./types";

/**
 * Prize library — reusable outcomes referenced by id in `wheelDatabase.ts`.
 * Add new prizes here, then reference them as `{ prize: "your_id", chance: 10 }`.
 */
export const PRIZE_CATALOG = {
  money_30: {
    kind: "money",
    label: "+$30",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 30 },
  },
  money_50: {
    kind: "money",
    label: "+$50",
    icon: "add-circle",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 50 },
    presentation: { colorIndex: 0 },
  },
  money_80: {
    kind: "money",
    label: "+$80",
    icon: "add-circle",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 80 },
  },
  money_100: {
    kind: "money",
    label: "+$100",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 100 },
  },
  money_120: {
    kind: "money",
    label: "+$120",
    icon: "add-circle",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 120 },
  },
  money_150: {
    kind: "money",
    label: "+$150",
    icon: "add-circle",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 150 },
  },
  money_200: {
    kind: "money",
    label: "+$200",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 200 },
  },
  money_300: {
    kind: "money",
    label: "+$300",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 300 },
  },
  money_500: {
    kind: "money",
    label: "+$500",
    icon: "emoji-events",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { moneyDelta: 500 },
  },
  money_600: {
    kind: "money",
    label: "+$60",
    icon: "add-circle",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { moneyDelta: 60 },
  },
  money_800: {
    kind: "money",
    label: "JACKPOT +$800",
    icon: "emoji-events",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { moneyDelta: 800 },
  },
  money_1000: {
    kind: "money",
    label: "JACKPOT +$1000",
    icon: "emoji-events",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { moneyDelta: 1000 },
  },
  money_loss_40: {
    kind: "money_loss",
    label: "-$40",
    icon: "remove-circle",
    iconFamily: "MaterialIcons",
    weightTags: ["negative"],
    payload: { moneyDelta: -40 },
  },
  money_loss_50: {
    kind: "money_loss",
    label: "-$50",
    icon: "remove-circle",
    iconFamily: "MaterialIcons",
    weightTags: ["negative"],
    payload: { moneyDelta: -50 },
  },
  money_loss_60: {
    kind: "money_loss",
    label: "-$60",
    icon: "remove-circle",
    iconFamily: "MaterialIcons",
    weightTags: ["negative"],
    payload: { moneyDelta: -60 },
  },
  money_loss_80: {
    kind: "money_loss",
    label: "-$80",
    icon: "remove-circle",
    iconFamily: "MaterialIcons",
    weightTags: ["negative"],
    payload: { moneyDelta: -80 },
  },
  money_loss_100: {
    kind: "money_loss",
    label: "-$100",
    icon: "remove-circle",
    iconFamily: "MaterialIcons",
    weightTags: ["negative"],
    payload: { moneyDelta: -100 },
  },
  money_loss_150: {
    kind: "money_loss",
    label: "-$150",
    icon: "remove-circle",
    iconFamily: "MaterialIcons",
    weightTags: ["negative", "stakes"],
    payload: { moneyDelta: -150 },
  },
  money_loss_200: {
    kind: "money_loss",
    label: "-$200",
    icon: "remove-circle",
    iconFamily: "MaterialIcons",
    weightTags: ["negative"],
    payload: { moneyDelta: -200 },
  },
  bank_cut_half: {
    kind: "bank_cut",
    label: "LOSE 50%",
    icon: "remove-circle",
    iconFamily: "MaterialIcons",
    weightTags: ["negative", "stakes"],
    payload: { bankPercent: -0.5 },
  },
  bank_cut_quarter: {
    kind: "bank_cut",
    label: "LOSE 25%",
    icon: "percent",
    iconFamily: "MaterialIcons",
    weightTags: ["negative", "stakes"],
    payload: { bankPercent: -0.25 },
  },
  bank_cut_75: {
    kind: "bank_cut",
    label: "LOSE 75%",
    icon: "remove-circle",
    iconFamily: "MaterialIcons",
    weightTags: ["negative", "stakes"],
    payload: { bankPercent: -0.75 },
  },
  bank_wipe: {
    kind: "bank_wipe",
    label: "LOSE ALL",
    icon: "dangerous",
    iconFamily: "MaterialIcons",
    weightTags: ["negative", "stakes", "rare"],
    payload: { wipeBank: true },
    presentation: { rarity: "rare" },
  },
  bank_double: {
    kind: "money",
    label: "DOUBLE $",
    icon: "attach-money",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { bankPercent: 1 },
  },
  perk_lucky_streak: {
    kind: "perk",
    label: "Lucky",
    icon: "stars",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "lucky_streak" },
    presentation: { rarity: "rare" },
  },
  perk_gold_rush: {
    kind: "perk",
    label: "Gold+",
    icon: "trending-up",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "gold_rush" },
    presentation: { rarity: "rare" },
  },
  perk_iron_reserve: {
    kind: "perk",
    label: "Iron Reserve",
    icon: "shield",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "iron_reserve" },
  },
  perk_safe_harbor: {
    kind: "perk",
    label: "Safe Harbor",
    icon: "security",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "safe_harbor" },
  },
  perk_high_roller: {
    kind: "perk",
    label: "High Roller",
    icon: "casino",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "high_roller" },
  },
  perk_hot_table: {
    kind: "perk",
    label: "Hot Table",
    icon: "whatshot",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "hot_table" },
  },
  perk_double_down: {
    kind: "perk",
    label: "Double Down",
    icon: "exposure-plus-1",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "double_down" },
  },
  perk_vip_roller: {
    kind: "perk",
    label: "VIP Roller",
    icon: "workspace-premium",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "vip_roller" },
  },
  perk_extra_slice: {
    kind: "perk",
    label: "+1 Slice",
    icon: "unfold-more",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "extra_slice" },
  },
  perk_ante_insurance: {
    kind: "perk",
    label: "Quota Shield",
    icon: "policy",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "ante_insurance" },
  },
  deck_copper_chip: {
    kind: "deck_add",
    label: "+Card",
    icon: "style",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { cardId: "copper_chip" },
  },
  deck_weighted_die: {
    kind: "deck_add",
    label: "Loaded Die",
    icon: "casino",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { cardId: "weighted_die" },
  },
  deck_upgrade: {
    kind: "deck_upgrade",
    label: "Upgrade Chip",
    icon: "upgrade",
    iconFamily: "MaterialCommunityIcons",
    payload: {},
  },
  deck_remove: {
    kind: "deck_remove",
    label: "Burn Chip",
    icon: "delete",
    iconFamily: "MaterialIcons",
    weightTags: ["negative"],
    payload: {},
  },
  debuff_debt_mark: {
    kind: "debuff",
    label: "Debt Mark",
    icon: "skull",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["negative"],
    payload: { debuffId: "debt_mark" },
  },
  debuff_rusted: {
    kind: "debuff",
    label: "Rusted",
    icon: "alert-octagon",
    iconFamily: "MaterialCommunityIcons",
    weightTags: ["negative"],
    payload: { debuffId: "rusted_gear" },
  },
  relic_lucky_coin: {
    kind: "relic_offer",
    label: "Lucky Coin",
    icon: "diamond",
    iconFamily: "MaterialIcons",
    weightTags: ["rare"],
    payload: { relicId: "lucky_coin" },
  },
  relic_void_lens: {
    kind: "relic_offer",
    label: "Void Lens",
    icon: "diamond",
    iconFamily: "MaterialIcons",
    weightTags: ["rare"],
    payload: { relicId: "void_lens" },
  },
  perk_compounder: {
    kind: "perk",
    label: "Compounder",
    icon: "savings",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "compounder" },
    presentation: { rarity: "rare" },
  },
  perk_coupon_king: {
    kind: "perk",
    label: "Coupon King",
    icon: "sell",
    iconFamily: "MaterialIcons",
    weightTags: ["positive", "rare"],
    payload: { perkId: "coupon_king" },
  },
  deck_purity_charm: {
    kind: "deck_add",
    label: "Purity Charm",
    icon: "favorite",
    iconFamily: "MaterialIcons",
    weightTags: ["positive"],
    payload: { cardId: "purity_charm" },
  },
  neutral_calm: {
    kind: "neutral",
    label: "Calm",
    icon: "spa",
    iconFamily: "MaterialIcons",
    payload: {},
  },
  neutral_hold: {
    kind: "neutral",
    label: "Hold",
    icon: "pan-tool",
    iconFamily: "MaterialIcons",
    payload: {},
  },
  neutral_focus: {
    kind: "neutral",
    label: "Focus",
    icon: "center-focus-strong",
    iconFamily: "MaterialIcons",
    payload: {},
  },
  neutral_gamble: {
    kind: "neutral",
    label: "Gamble",
    icon: "casino",
    iconFamily: "MaterialIcons",
    payload: {},
  },
  neutral: {
    kind: "neutral",
    label: "—",
    icon: "skip-next",
    iconFamily: "MaterialIcons",
    payload: {},
  },
} as const satisfies Record<string, PrizeDef>;

export type PrizeCatalogId = keyof typeof PRIZE_CATALOG;
